export const COUNTRIES = [
  { code: "AF", label_en: "Afghanistan", label_it: "Afghanistan" },
  { code: "AL", label_en: "Albania", label_it: "Albania" },
  { code: "DZ", label_en: "Algeria", label_it: "Algeria" },
  { code: "AD", label_en: "Andorra", label_it: "Andorra" },
  { code: "AO", label_en: "Angola", label_it: "Angola" },
  { code: "AG", label_en: "Antigua and Barbuda", label_it: "Antigua e Barbuda" },
  { code: "AR", label_en: "Argentina", label_it: "Argentina" },
  { code: "AM", label_en: "Armenia", label_it: "Armenia" },
  { code: "AU", label_en: "Australia", label_it: "Australia" },
  { code: "AT", label_en: "Austria", label_it: "Austria" },
  { code: "AZ", label_en: "Azerbaijan", label_it: "Azerbaigian" },
  { code: "BS", label_en: "Bahamas", label_it: "Bahamas" },
  { code: "BH", label_en: "Bahrain", label_it: "Bahrein" },
  { code: "BD", label_en: "Bangladesh", label_it: "Bangladesh" },
  { code: "BB", label_en: "Barbados", label_it: "Barbados" },
  { code: "BY", label_en: "Belarus", label_it: "Bielorussia" },
  { code: "BE", label_en: "Belgium", label_it: "Belgio" },
  { code: "BZ", label_en: "Belize", label_it: "Belize" },
  { code: "BJ", label_en: "Benin", label_it: "Benin" },
  { code: "BT", label_en: "Bhutan", label_it: "Bhutan" },
  { code: "BO", label_en: "Bolivia", label_it: "Bolivia" },
  { code: "BA", label_en: "Bosnia and Herzegovina", label_it: "Bosnia ed Erzegovina" },
  { code: "BW", label_en: "Botswana", label_it: "Botswana" },
  { code: "BR", label_en: "Brazil", label_it: "Brasile" },
  { code: "BN", label_en: "Brunei", label_it: "Brunei" },
  { code: "BG", label_en: "Bulgaria", label_it: "Bulgaria" },
  { code: "BF", label_en: "Burkina Faso", label_it: "Burkina Faso" },
  { code: "BI", label_en: "Burundi", label_it: "Burundi" },
  { code: "CV", label_en: "Cabo Verde", label_it: "Capo Verde" },
  { code: "KH", label_en: "Cambodia", label_it: "Cambogia" },
  { code: "CM", label_en: "Cameroon", label_it: "Camerun" },
  { code: "CA", label_en: "Canada", label_it: "Canada" },
  { code: "CF", label_en: "Central African Republic", label_it: "Repubblica Centrafricana" },
  { code: "TD", label_en: "Chad", label_it: "Ciad" },
  { code: "CL", label_en: "Chile", label_it: "Cile" },
  { code: "CN", label_en: "China", label_it: "Cina" },
  { code: "CO", label_en: "Colombia", label_it: "Colombia" },
  { code: "KM", label_en: "Comoros", label_it: "Comore" },
  { code: "CG", label_en: "Congo", label_it: "Congo" },
  { code: "CD", label_en: "Democratic Republic of the Congo", label_it: "Repubblica Democratica del Congo" },
  { code: "CR", label_en: "Costa Rica", label_it: "Costa Rica" },
  { code: "CI", label_en: "Cote d'Ivoire", label_it: "Costa d'Avorio" },
  { code: "HR", label_en: "Croatia", label_it: "Croazia" },
  { code: "CU", label_en: "Cuba", label_it: "Cuba" },
  { code: "CY", label_en: "Cyprus", label_it: "Cipro" },
  { code: "CZ", label_en: "Czech Republic", label_it: "Repubblica Ceca" },
  { code: "DK", label_en: "Denmark", label_it: "Danimarca" },
  { code: "DJ", label_en: "Djibouti", label_it: "Gibuti" },
  { code: "DM", label_en: "Dominica", label_it: "Dominica" },
  { code: "DO", label_en: "Dominican Republic", label_it: "Repubblica Dominicana" },
  { code: "EC", label_en: "Ecuador", label_it: "Ecuador" },
  { code: "EG", label_en: "Egypt", label_it: "Egitto" },
  { code: "SV", label_en: "El Salvador", label_it: "El Salvador" },
  { code: "GQ", label_en: "Equatorial Guinea", label_it: "Guinea Equatoriale" },
  { code: "ER", label_en: "Eritrea", label_it: "Eritrea" },
  { code: "EE", label_en: "Estonia", label_it: "Estonia" },
  { code: "SZ", label_en: "Eswatini", label_it: "Eswatini" },
  { code: "ET", label_en: "Ethiopia", label_it: "Etiopia" },
  { code: "FJ", label_en: "Fiji", label_it: "Figi" },
  { code: "FI", label_en: "Finland", label_it: "Finlandia" },
  { code: "FR", label_en: "France", label_it: "Francia" },
  { code: "GA", label_en: "Gabon", label_it: "Gabon" },
  { code: "GM", label_en: "Gambia", label_it: "Gambia" },
  { code: "GE", label_en: "Georgia", label_it: "Georgia" },
  { code: "DE", label_en: "Germany", label_it: "Germania" },
  { code: "GH", label_en: "Ghana", label_it: "Ghana" },
  { code: "GR", label_en: "Greece", label_it: "Grecia" },
  { code: "GD", label_en: "Grenada", label_it: "Grenada" },
  { code: "GT", label_en: "Guatemala", label_it: "Guatemala" },
  { code: "GN", label_en: "Guinea", label_it: "Guinea" },
  { code: "GW", label_en: "Guinea-Bissau", label_it: "Guinea-Bissau" },
  { code: "GY", label_en: "Guyana", label_it: "Guyana" },
  { code: "HT", label_en: "Haiti", label_it: "Haiti" },
  { code: "HN", label_en: "Honduras", label_it: "Honduras" },
  { code: "HU", label_en: "Hungary", label_it: "Ungheria" },
  { code: "IS", label_en: "Iceland", label_it: "Islanda" },
  { code: "IN", label_en: "India", label_it: "India" },
  { code: "ID", label_en: "Indonesia", label_it: "Indonesia" },
  { code: "IR", label_en: "Iran", label_it: "Iran" },
  { code: "IQ", label_en: "Iraq", label_it: "Iraq" },
  { code: "IE", label_en: "Ireland", label_it: "Irlanda" },
  { code: "IL", label_en: "Israel", label_it: "Israele" },
  { code: "IT", label_en: "Italy", label_it: "Italia" },
  { code: "JM", label_en: "Jamaica", label_it: "Giamaica" },
  { code: "JP", label_en: "Japan", label_it: "Giappone" },
  { code: "JO", label_en: "Jordan", label_it: "Giordania" },
  { code: "KZ", label_en: "Kazakhstan", label_it: "Kazakistan" },
  { code: "KE", label_en: "Kenya", label_it: "Kenya" },
  { code: "KI", label_en: "Kiribati", label_it: "Kiribati" },
  { code: "KP", label_en: "North Korea", label_it: "Corea del Nord" },
  { code: "KR", label_en: "South Korea", label_it: "Corea del Sud" },
  { code: "KW", label_en: "Kuwait", label_it: "Kuwait" },
  { code: "KG", label_en: "Kyrgyzstan", label_it: "Kirghizistan" },
  { code: "LA", label_en: "Laos", label_it: "Laos" },
  { code: "LV", label_en: "Latvia", label_it: "Lettonia" },
  { code: "LB", label_en: "Lebanon", label_it: "Libano" },
  { code: "LS", label_en: "Lesotho", label_it: "Lesotho" },
  { code: "LR", label_en: "Liberia", label_it: "Liberia" },
  { code: "LY", label_en: "Libya", label_it: "Libia" },
  { code: "LI", label_en: "Liechtenstein", label_it: "Liechtenstein" },
  { code: "LT", label_en: "Lithuania", label_it: "Lituania" },
  { code: "LU", label_en: "Luxembourg", label_it: "Lussemburgo" },
  { code: "MG", label_en: "Madagascar", label_it: "Madagascar" },
  { code: "MW", label_en: "Malawi", label_it: "Malawi" },
  { code: "MY", label_en: "Malaysia", label_it: "Malesia" },
  { code: "MV", label_en: "Maldives", label_it: "Maldive" },
  { code: "ML", label_en: "Mali", label_it: "Mali" },
  { code: "MT", label_en: "Malta", label_it: "Malta" },
  { code: "MH", label_en: "Marshall Islands", label_it: "Isole Marshall" },
  { code: "MR", label_en: "Mauritania", label_it: "Mauritania" },
  { code: "MU", label_en: "Mauritius", label_it: "Mauritius" },
  { code: "MX", label_en: "Mexico", label_it: "Messico" },
  { code: "FM", label_en: "Micronesia", label_it: "Micronesia" },
  { code: "MD", label_en: "Moldova", label_it: "Moldavia" },
  { code: "MC", label_en: "Monaco", label_it: "Monaco" },
  { code: "MN", label_en: "Mongolia", label_it: "Mongolia" },
  { code: "ME", label_en: "Montenegro", label_it: "Montenegro" },
  { code: "MA", label_en: "Morocco", label_it: "Marocco" },
  { code: "MZ", label_en: "Mozambique", label_it: "Mozambico" },
  { code: "MM", label_en: "Myanmar", label_it: "Myanmar" },
  { code: "NA", label_en: "Namibia", label_it: "Namibia" },
  { code: "NR", label_en: "Nauru", label_it: "Nauru" },
  { code: "NP", label_en: "Nepal", label_it: "Nepal" },
  { code: "NL", label_en: "Netherlands", label_it: "Paesi Bassi" },
  { code: "NZ", label_en: "New Zealand", label_it: "Nuova Zelanda" },
  { code: "NI", label_en: "Nicaragua", label_it: "Nicaragua" },
  { code: "NE", label_en: "Niger", label_it: "Niger" },
  { code: "NG", label_en: "Nigeria", label_it: "Nigeria" },
  { code: "MK", label_en: "North Macedonia", label_it: "Macedonia del Nord" },
  { code: "NO", label_en: "Norway", label_it: "Norvegia" },
  { code: "OM", label_en: "Oman", label_it: "Oman" },
  { code: "PK", label_en: "Pakistan", label_it: "Pakistan" },
  { code: "PW", label_en: "Palau", label_it: "Palau" },
  { code: "PA", label_en: "Panama", label_it: "Panama" },
  { code: "PG", label_en: "Papua New Guinea", label_it: "Papua Nuova Guinea" },
  { code: "PY", label_en: "Paraguay", label_it: "Paraguay" },
  { code: "PE", label_en: "Peru", label_it: "Peru" },
  { code: "PH", label_en: "Philippines", label_it: "Filippine" },
  { code: "PL", label_en: "Poland", label_it: "Polonia" },
  { code: "PT", label_en: "Portugal", label_it: "Portogallo" },
  { code: "QA", label_en: "Qatar", label_it: "Qatar" },
  { code: "RO", label_en: "Romania", label_it: "Romania" },
  { code: "RU", label_en: "Russia", label_it: "Russia" },
  { code: "RW", label_en: "Rwanda", label_it: "Ruanda" },
  { code: "KN", label_en: "Saint Kitts and Nevis", label_it: "Saint Kitts e Nevis" },
  { code: "LC", label_en: "Saint Lucia", label_it: "Saint Lucia" },
  { code: "VC", label_en: "Saint Vincent and the Grenadines", label_it: "Saint Vincent e Grenadine" },
  { code: "WS", label_en: "Samoa", label_it: "Samoa" },
  { code: "SM", label_en: "San Marino", label_it: "San Marino" },
  { code: "ST", label_en: "Sao Tome and Principe", label_it: "Sao Tome e Principe" },
  { code: "SA", label_en: "Saudi Arabia", label_it: "Arabia Saudita" },
  { code: "SN", label_en: "Senegal", label_it: "Senegal" },
  { code: "RS", label_en: "Serbia", label_it: "Serbia" },
  { code: "SC", label_en: "Seychelles", label_it: "Seychelles" },
  { code: "SL", label_en: "Sierra Leone", label_it: "Sierra Leone" },
  { code: "SG", label_en: "Singapore", label_it: "Singapore" },
  { code: "SK", label_en: "Slovakia", label_it: "Slovacchia" },
  { code: "SI", label_en: "Slovenia", label_it: "Slovenia" },
  { code: "SB", label_en: "Solomon Islands", label_it: "Isole Salomone" },
  { code: "SO", label_en: "Somalia", label_it: "Somalia" },
  { code: "ZA", label_en: "South Africa", label_it: "Sudafrica" },
  { code: "SS", label_en: "South Sudan", label_it: "Sud Sudan" },
  { code: "ES", label_en: "Spain", label_it: "Spagna" },
  { code: "LK", label_en: "Sri Lanka", label_it: "Sri Lanka" },
  { code: "SD", label_en: "Sudan", label_it: "Sudan" },
  { code: "SR", label_en: "Suriname", label_it: "Suriname" },
  { code: "SE", label_en: "Sweden", label_it: "Svezia" },
  { code: "CH", label_en: "Switzerland", label_it: "Svizzera" },
  { code: "SY", label_en: "Syria", label_it: "Siria" },
  { code: "TW", label_en: "Taiwan", label_it: "Taiwan" },
  { code: "TJ", label_en: "Tajikistan", label_it: "Tagikistan" },
  { code: "TZ", label_en: "Tanzania", label_it: "Tanzania" },
  { code: "TH", label_en: "Thailand", label_it: "Thailandia" },
  { code: "TL", label_en: "Timor-Leste", label_it: "Timor Est" },
  { code: "TG", label_en: "Togo", label_it: "Togo" },
  { code: "TO", label_en: "Tonga", label_it: "Tonga" },
  { code: "TT", label_en: "Trinidad and Tobago", label_it: "Trinidad e Tobago" },
  { code: "TN", label_en: "Tunisia", label_it: "Tunisia" },
  { code: "TR", label_en: "Turkey", label_it: "Turchia" },
  { code: "TM", label_en: "Turkmenistan", label_it: "Turkmenistan" },
  { code: "TV", label_en: "Tuvalu", label_it: "Tuvalu" },
  { code: "UG", label_en: "Uganda", label_it: "Uganda" },
  { code: "UA", label_en: "Ukraine", label_it: "Ucraina" },
  { code: "AE", label_en: "United Arab Emirates", label_it: "Emirati Arabi Uniti" },
  { code: "GB", label_en: "United Kingdom", label_it: "Regno Unito" },
  { code: "US", label_en: "United States", label_it: "Stati Uniti" },
  { code: "UY", label_en: "Uruguay", label_it: "Uruguay" },
  { code: "UZ", label_en: "Uzbekistan", label_it: "Uzbekistan" },
  { code: "VU", label_en: "Vanuatu", label_it: "Vanuatu" },
  { code: "VA", label_en: "Vatican City", label_it: "Citta del Vaticano" },
  { code: "VE", label_en: "Venezuela", label_it: "Venezuela" },
  { code: "VN", label_en: "Vietnam", label_it: "Vietnam" },
  { code: "YE", label_en: "Yemen", label_it: "Yemen" },
  { code: "ZM", label_en: "Zambia", label_it: "Zambia" },
  { code: "ZW", label_en: "Zimbabwe", label_it: "Zimbabwe" },
];

export function getCountryOptions(locale = "it") {
  const lang = locale === "en" ? "en" : "it";

  return COUNTRIES.map((country) => ({
    code: country.code,
    label: lang === "en" ? country.label_en : country.label_it,
    label_en: country.label_en,
    label_it: country.label_it,
  }));
}

export function getCountryLabel(code, locale = "it") {
  const lang = locale === "en" ? "en" : "it";
  const match = COUNTRIES.find((country) => country.code === code);
  if (!match) return "";
  return lang === "en" ? match.label_en : match.label_it;
}

export function getCountryLabelEn(code) {
  const match = COUNTRIES.find((country) => country.code === code);
  return match?.label_en || "";
}

export function buildCityWithCountry(city, countryCode) {
  const cityClean = String(city || "").trim();
  const countryEn = getCountryLabelEn(countryCode);

  if (!cityClean) return "";
  if (!countryEn) return cityClean;

  return `${cityClean}, ${countryEn}`;
}